spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_management
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
springdoc:
  swagger-ui:
    tags-sorter: alpha
    doc-expansion: false