spring:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/student_db
      username: root
      password: Vi-222777
      driver-class-name: com.mysql.cj.jdbc.Driver
    pg:
      url: jdbc:postgresql://localhost:5432/student_db
      username: postgres
      password: 123
      driver-class-name: org.postgresql.Driver
    oracle:
      url: jdbc:oracle:thin:@localhost:1521/XEPDB1
      username: system
      password: oracle
      driver-class-name: oracle.jdbc.OracleDriver

  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
    open-in-view: false